// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftbpgegxpmwvaqzyabcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0YnBnZWd4cG13dmFxenlhYmNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTMwNzksImV4cCI6MjA3NDM4OTA3OX0.m0kuIcXXevfDAhUErk0ugZ9NvLeblX6OBOmA42SNVe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});